# Generated by Django 2.0.3 on 2019-06-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_eng', models.TextField(null=True)),
                ('title_afr', models.TextField(null=True)),
                ('title_spa', models.TextField(null=True)),
                ('title_xho', models.TextField(null=True)),
                ('title_nso', models.TextField(null=True)),
                ('title_por', models.TextField(null=True)),
                ('title_sot', models.TextField(null=True)),
                ('title_tsn', models.TextField(null=True)),
                ('title_zul', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('question_eng', models.TextField(null=True)),
                ('question_afr', models.TextField(null=True)),
                ('question_spa', models.TextField(null=True)),
                ('question_xho', models.TextField(null=True)),
                ('question_nso', models.TextField(null=True)),
                ('question_por', models.TextField(null=True)),
                ('question_sot', models.TextField(null=True)),
                ('question_tsn', models.TextField(null=True)),
                ('question_zul', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('description_eng', models.TextField(null=True)),
                ('description_afr', models.TextField(null=True)),
                ('description_spa', models.TextField(null=True)),
                ('description_xho', models.TextField(null=True)),
                ('description_nso', models.TextField(null=True)),
                ('description_por', models.TextField(null=True)),
                ('description_sot', models.TextField(null=True)),
                ('description_tsn', models.TextField(null=True)),
                ('description_zul', models.TextField(null=True)),
                ('text_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_eng', models.TextField(null=True)),
                ('title_afr', models.TextField(null=True)),
                ('title_spa', models.TextField(null=True)),
                ('title_xho', models.TextField(null=True)),
                ('title_nso', models.TextField(null=True)),
                ('title_por', models.TextField(null=True)),
                ('title_sot', models.TextField(null=True)),
                ('title_tsn', models.TextField(null=True)),
                ('title_zul', models.TextField(null=True)),
                ('body', models.TextField()),
                ('body_eng', models.TextField(null=True)),
                ('body_afr', models.TextField(null=True)),
                ('body_spa', models.TextField(null=True)),
                ('body_xho', models.TextField(null=True)),
                ('body_nso', models.TextField(null=True)),
                ('body_por', models.TextField(null=True)),
                ('body_sot', models.TextField(null=True)),
                ('body_tsn', models.TextField(null=True)),
                ('body_zul', models.TextField(null=True)),
                ('Folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_api.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_eng', models.TextField(null=True)),
                ('title_afr', models.TextField(null=True)),
                ('title_spa', models.TextField(null=True)),
                ('title_xho', models.TextField(null=True)),
                ('title_nso', models.TextField(null=True)),
                ('title_por', models.TextField(null=True)),
                ('title_sot', models.TextField(null=True)),
                ('title_tsn', models.TextField(null=True)),
                ('title_zul', models.TextField(null=True)),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_api.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_api.Template'),
        ),
        migrations.AddField(
            model_name='folder',
            name='Icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_api.Icon'),
        ),
    ]
