# Generated by Django 2.0.3 on 2019-06-08 06:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_afr',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_eng',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_nso',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_por',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_sot',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_spa',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_tsn',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_xho',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='body_zul',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
