# Generated by Django 2.0.3 on 2019-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_api', '0002_auto_20190608_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_type',
            field=models.CharField(choices=[('text', 'text'), ('textarea', 'textarea')], max_length=20, null=True),
        ),
    ]
