"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%xwe=4ht+8()@%qnwp#iw4nl6@t^fd2*q+c$v$p8_zxi8+w-s@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'folder_api',
    'modeltranslation',
    'markdownx',
    'rest_hooks',
]

HOOK_EVENTS = {
    # 'any.event.name': 'App.Model.Action' (created/updated/deleted)
    'folder.added':       'folder_api.Folder.created',
    'folder.changed':     'folder_api.Folder.updated+',
    'folder.removed':     'folder_api.Folder.deleted',
    # and custom events, no extra meta data needed
    'folder.read':         'folder_api.Folder.read',
    # 'any.event.name': 'App.Model.Action' (created/updated/deleted)
    'resource.added':       'folder_api.Resource.created',
    'resource.changed':     'folder_api.Resource.updated+',
    'resource.removed':     'folder_api.Resource.deleted',
    # and custom events, no extra meta data needed
    'resource.read':         'folder_api.Resource.read',
    # 'any.event.name': 'App.Model.Action' (created/updated/deleted)
    'question.added':       'folder_api.Question.created',
    'question.changed':     'folder_api.Question.updated+',
    'question.removed':     'folder_api.Question.deleted',
    # and custom events, no extra meta data needed
    'question.read':         'folder_api.Question.read',
    
}

LANGUAGES = (
    ('eng', 'English'),
    ('afr', 'Afrikaans'),
    ('spa', 'Español'),
    ('xho', 'IsiXhosa'),
    ('nso', 'Nso Language'),
    ('por', 'Português'),
    ('sot', 'Southern Sotho'),
    ('tsn', 'Tswana'),
    ('zul', 'isiZulu'),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'eng'

MODELTRANSLATION_AUTO_POPULATE = True

MODELTRANSLATION_DEBUG = True


CORS_ORIGIN_ALLOW_ALL = True

# CORS_ORIGIN_WHITELIST = (
#        'localhost:3000',
#        'localhost:8000',
#        'coteacherv1.eastus.cloudapp.azure.com',
# )
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
